"""empty message

Revision ID: 2fbc2bcf96ca
Revises: 12d5cb78b84f
Create Date: 2018-09-23 20:17:15.043945

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2fbc2bcf96ca'
down_revision = '12d5cb78b84f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('symbol', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('sector', sa.String(length=250), nullable=True),
    sa.Column('employees', sa.Integer(), nullable=True),
    sa.Column('market', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('symbol'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('prices',
    sa.Column('symbol', sa.String(length=15), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['companies.symbol'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('symbol', 'date')
    )
    op.drop_table('comments')
    op.drop_table('categories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('categories_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='categories_pkey'),
    sa.UniqueConstraint('name', name='categories_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('comment', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('creation_date', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='comments_category_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='comments_pkey')
    )
    op.drop_table('prices')
    op.drop_table('companies')
    # ### end Alembic commands ###
