"""empty message

Revision ID: 37905e3a60b8
Revises: b6e01c9a264c
Create Date: 2018-11-08 23:26:53.111578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37905e3a60b8'
down_revision = 'b6e01c9a264c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
